[project]
title = "CyberOps"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
title = "CyberOps Volunteer Dashboard"
favicon = "images/favicon.ico"
logo = "images/logo.png"
theme = "dark"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 